### ISSUE TITLE
403 bad request

### ISSUE THREAD

**Issue by marlonn** [RushanKhan1/termTranslate#1]
I got the following output on my Ubuntu 20.04 desktop:

```
 ~> tran de test
GotError [HTTPError]: Response code 403 (Forbidden)
Url: https://translate.google.com/translate_a/single?client=t&sl=auto&tl=de&hl=de&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=test%20&tk=575829.575829
    at EventEmitter.<anonymous> (/home/rynnon/Downloads/termTranslate/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  host: 'translate.google.com',
  hostname: 'translate.google.com',
  method: 'GET',
  path: '/translate_a/single?client=t&sl=auto&tl=de&hl=de&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=test%20&tk=575829.575829',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://translate.google.com/translate_a/single?client=t&sl=auto&tl=de&hl=de&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=test%20&tk=575829.575829',
  gotOptions: {
    path: '/translate_a/single?client=t&sl=auto&tl=de&hl=de&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=test%20&tk=575829.575829',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'translate.google.com',
    port: null,
    hostname: 'translate.google.com',
    hash: null,
    search: '?client=t&sl=auto&tl=de&hl=de&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=test%20&tk=575829.575829',
    pathname: '/translate_a/single',
    href: 'https://translate.google.com/translate_a/single?client=t&sl=auto&tl=de&hl=de&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=test%20&tk=575829.575829',
    retry: {
      retries: [Function],
      methods: [Set],
      statusCodes: [Set],
      errorCodes: [Set]
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: false,
    form: false,
    json: false,
    cache: false,
    useElectronNet: false,
    method: 'GET'
  },
  statusCode: 403,
  statusMessage: 'Forbidden',
  headers: {
    'content-type': 'text/html; charset=utf-8',
    'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
    pragma: 'no-cache',
    expires: 'Mon, 01 Jan 1990 00:00:00 GMT',
    date: 'Thu, 27 May 2021 12:02:40 GMT',
    p3p: 'CP="This is not a P3P policy! See g.co/p3phelp for more info."',
    'cross-origin-resource-policy': 'cross-origin',
    'cross-origin-opener-policy': 'same-origin; report-to="TranslateApiHttp"',
    'report-to': '{"group":"TranslateApiHttp","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/TranslateApiHttp/external"}]}',
    'content-security-policy': "script-src 'report-sample' 'nonce-CcfKEZpKep59dcUif6tgxQ' 'unsafe-inline';object-src 'none';base-uri 'self';report-uri /_/TranslateApiHttp/cspreport;worker-src 'self'",
    'content-encoding': 'gzip',
    server: 'ESF',
    'x-xss-protection': '0',
    'x-content-type-options': 'nosniff',
    'set-cookie': [
      'NID=216=ksTv6585T36uwBQHdaOZpzsBJtz-bH0yT8oBqk-PYF-ragMcQXELRQq4Irs-RwB94VD0qH6YaBd4GPSbIRBHjwIoIn6x3JqZcTHOA7JxFwesdNlyHr1s_sdTZZ7RUGkYNZpXzq8XJKYegiRs26b2wkOHQu25TX114KT9y3xpSAw; expires=Fri, 26-Nov-2021 12:02:40 GMT; path=/; domain=.google.com; HttpOnly'
    ],
    'alt-svc': 'h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
    connection: 'close',
    'transfer-encoding': 'chunked'
  },
  body: '<html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width"><title>Error 403 (Verboten)!!1</title><style nonce="lFc5oymRWUvM0+x2UF5M6g">*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{color:#222;text-align:unset;margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px;}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}pre{white-space:pre-wrap;}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}</style><div id="af-error-container"><a href=//www.google.com><span id=logo aria-label=Google></span></a><p><b>403.</b> <ins>Dies ist ein Fehler.</ins><p>Du hast keinen Zugriff auf diese Seite. <ins>Keine weiteren Informationen vorhanden.</ins></div>',
  code: 'BAD_REQUEST'
}

```

I believe I followed the install instructions correctly and double-checked that ~/node_modules and ~/.npm is in my PATH, but who knows.

**Comment by RushanKhan1** [comment]
I looked around and found that I was using an old version of the [npm package](https://www.npmjs.com/package/@vitalets/google-translate-api) which sometimes did have the problem that you are facing ([#60](https://github.com/vitalets/google-translate-api/issues/60)). I have updated it to the latest version as they suggested so please try reinstalling and tell me if it works.

**Comment by marlonn** [comment]
It works now, thanks!
